apiVersion: caas.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: app-cluster-1
  namespace: default
spec:
  parameters:
    cloud: aws
    deletionPolicy: Delete
    id: app-cluster-1
    providerConfigName: default
    region: us-east-1
    version: "1.28"
    gitops:
      operator: argocd
      git:
        url: https://github.com/upbound-demo/space-demo-monorepo.git
        ref:
          name: refs/heads/main
    nodes:
      count: 2
      instanceType: t3.medium
  writeConnectionSecretToRef:
    name: appcluster-1-kubeconfig
