apiVersion: spaces.upbound.io/v1alpha1
kind: SharedExternalSecret
metadata:
  name: providerconfig-creds-test
  namespace: playground
  labels:
    acmeco/team: playground
    acmeco/environment: test
spec:
  controlPlaneSelector:
    labelSelectors:
      - matchLabels:
          acmeco/environment: test
  namespaceSelector:
    names:
      - default
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: aws-secretsmanager
      kind: ClusterSecretStore
    target:
      template:
        engineVersion: v2
        data:
          name: providerconfig-creds-test
          access-key: "{{ index .data "access-key" }}"             
          secret-access-key: "{{ index .data ".secret-access-key" }}"   
    data:
    - secretKey: secret-access-key
      remoteRef:
        key: providerconfig-creds-test
    - secretKey: access-key
      remoteRef:
        key: providerconfig-creds-test