apiVersion: spaces.upbound.io/v1alpha1
kind: SharedExternalSecret
metadata:
  name: providerconfig-creds-test
  namespace: consumer-services
  labels:
    acmeco/team: consumer-services
    acmeco/environment: test
spec:
  controlPlaneSelector:
    labelSelectors:
      - matchLabels:
          acmeco/environment: test
  namespaceSelector:
    names:
      - default
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: aws-secretsmanager
      kind: ClusterSecretStore
    target:
      template:
        engineVersion: v2
        data:
          creds: |
            [default]
            aws_access_key_id = {{ .accessKey }}
            aws_secret_access_key = {{ .secretAccessKey }}
    data:
    - secretKey: accessKey
      remoteRef:
        key: providerconfig-creds-test
        property: access-key
    - secretKey: secretAccessKey
      remoteRef:
        key: providerconfig-creds-test
        property: secret-access-key