apiVersion: spaces.upbound.io/v1alpha1
kind: SharedBackupConfig
metadata:
  name: default
  namespace: consumer-services
  labels:
    acmeco/team: consumer-services
    acmeco/environment: prod
    acmeco/environment: test
spec:
  objectStorage:
    provider: AWS
    bucket: spaces-1-backup-bucket
    config:
      endpoint: s3.us-west-1.amazonaws.com
      region: us-west-1
    credentials:
      source: Secret
      secretRef:
        name: bucket-creds
        key: creds